print("=============================")
print("     Teknik Informatika      ")
print("=============================")
print("Nama  : Dimas Bayu Cahya Putra")
print("Nim   : B34180015")
print("Prodi : Teknik Informatika 2018 A")
print("Univ  : UNIVERSITAS NAHDLATUL ULAMA SIDOARJO")
